### ISSUE TITLE
How would you rate Broken

### ISSUE THREAD

**Issue by atutor** [classcentral/class-central#37]
We've had a couple people in our latest course report that the star selection in question 1 of a course review is not taking. I can confirm that once moving the mouse pointer away, the stars become unselected.

https://www.class-central.com/review/new/9272#

Hoping you can correct this quickly, as our course is ending and we don't wan't to miss the opportunity to collect some participant ratings.

thanks
greg

**Comment by scottusrobus** [comment]
Hi Greg (@atutor),

Thanks for the bug report!

I was able to replicate the issue in some versions of Firefox. I assume that's where you saw the bug as well? We've pushed up a fix. Can you confirm it works as expected?

**Comment by atutor** [comment]
Yes, seems to be working now. 
Thanks for the quick fix!

**Comment by scottusrobus** [comment]
great! thanks again for the report!
